<a href="https://colab.research.google.com/github/Nirmal-Narasimha/FeatureSelection/blob/main/wrapper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.tree import DecisionTreeClassifier

In [67]:
cr = pd.read_csv("diabetes.csv")

In [68]:
select = SelectFromModel(RandomForestClassifier(n_estimators=100))

In [69]:
cr.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [70]:
cr.shape

(768, 9)

In [71]:
select = SelectFromModel(RandomForestClassifier(n_estimators=100))
cr_x = cr.iloc[:, 0:8]
cr_y = cr.iloc[:, -1]

In [72]:
select.fit(cr_x, cr_y)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                                 class_weight=None,
                                                 criterion='gini',
                                                 max_depth=None,
                                                 max_features='auto',
                                                 max_leaf_nodes=None,
                                                 max_samples=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=100, n_jobs=None,
                                                 oob_score=False,

In [73]:
select.get_support()

array([False,  True, False, False, False,  True,  True,  True])

In [74]:
cr_x.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [75]:
list1 = list(select.get_support())

In [76]:
list1

[False, True, False, False, False, True, True, True]

In [77]:
#True is importane and 0 isnt important
df_feat_imp = pd.DataFrame({"Feature_Name":cr_x.columns, "Importance":list1})
df_feat_imp

Feature_Name  Importance
0               Pregnancies       False
1                   Glucose        True
2             BloodPressure       False
3             SkinThickness       False
4                   Insulin       False
5                       BMI        True
6  DiabetesPedigreeFunction        True
7                       Age        True

In [78]:
df_feat_imp.sort_values(["Importance"], ascending = False)

Feature_Name  Importance
1                   Glucose        True
5                       BMI        True
6  DiabetesPedigreeFunction        True
7                       Age        True
0               Pregnancies       False
2             BloodPressure       False
3             SkinThickness       False
4                   Insulin       False

In [79]:
#Second Method
rfc = RandomForestClassifier()
rfc.fit(cr_x, cr_y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [80]:
rfc.feature_importances_ #Higher score more important feature

array([0.08274233, 0.25738625, 0.09135143, 0.0682386 , 0.07307608,
       0.16050109, 0.12632089, 0.14038335])

In [81]:
cr_x.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [82]:
df1 = pd.DataFrame({"feature_name": cr_x.columns, "Importance":list(rfc.feature_importances_)})

In [83]:
df1

feature_name  Importance
0               Pregnancies    0.082742
1                   Glucose    0.257386
2             BloodPressure    0.091351
3             SkinThickness    0.068239
4                   Insulin    0.073076
5                       BMI    0.160501
6  DiabetesPedigreeFunction    0.126321
7                       Age    0.140383

In [84]:
df1.sort_values(["Importance"], ascending=False)

feature_name  Importance
1                   Glucose    0.257386
5                       BMI    0.160501
7                       Age    0.140383
6  DiabetesPedigreeFunction    0.126321
2             BloodPressure    0.091351
0               Pregnancies    0.082742
4                   Insulin    0.073076
3             SkinThickness    0.068239

In [85]:
##3rd
from sklearn.tree import DecisionTreeClassifier

In [86]:
dt = DecisionTreeClassifier()
dt.fit(cr_x, cr_y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [87]:
dt.feature_importances_

array([0.04677455, 0.33268653, 0.08679506, 0.02670953, 0.0421772 ,
       0.22713309, 0.11791617, 0.11980788])

In [88]:
dt.feature_importances_.sum()

0.9999999999999999

In [89]:
#4th CHIsquare
test = SelectKBest(score_func=chi2, k="all")#to check corelation on all k features


In [90]:
fited = test.fit(cr_x, cr_y)

In [91]:
fited.scores_

array([ 111.51969064, 1411.88704064,   17.60537322,   53.10803984,
       2175.56527292,  127.66934333,    5.39268155,  181.30368904])

In [92]:
list(fited.scores_)#Higher value more important

[111.51969063588255,
 1411.887040644141,
 17.605373215320718,
 53.10803983632434,
 2175.5652729220137,
 127.669343331037,
 5.392681546971445,
 181.30368904430023]

In [93]:
df2 = pd.DataFrame({"Features":cr_x.columns, "Imp":list(fited.scores_)})
df2

Features          Imp
0               Pregnancies   111.519691
1                   Glucose  1411.887041
2             BloodPressure    17.605373
3             SkinThickness    53.108040
4                   Insulin  2175.565273
5                       BMI   127.669343
6  DiabetesPedigreeFunction     5.392682
7                       Age   181.303689

In [94]:
df2.sort_values(["Imp"],ascending=False)

Features          Imp
4                   Insulin  2175.565273
1                   Glucose  1411.887041
7                       Age   181.303689
5                       BMI   127.669343
0               Pregnancies   111.519691
3             SkinThickness    53.108040
2             BloodPressure    17.605373
6  DiabetesPedigreeFunction     5.392682

In [95]:
#Boruta Runs multiple random forests giving 3 values Confirm,Tentative,Rejected
start = pd.read_csv("Data.csv")
start.head()


Sample code number  Clump Thickness  ...  Mitoses  Class
0             1000025                5  ...        1      2
1             1002945                5  ...        1      2
2             1015425                3  ...        1      2
3             1016277                6  ...        1      2
4             1017023                4  ...        1      2

[5 rows x 11 columns]

In [96]:
start_x = start.iloc[:,1:10]
start_y = start.iloc[:, -1]

In [97]:
start.shape

(683, 11)

In [98]:
import numpy as np
start_x = np.array(start_x)
start_y = np.array(start_y)

In [99]:
!pip install boruta

In [100]:
from boruta import BorutaPy

In [101]:
rf = RandomForestClassifier()

In [102]:
boruta_feature_selector = BorutaPy(rf, random_state=111,max_iter=50,perc=100,verbose=2)#Runs random Forest for 50times,perc=Be sure when selecting feature 100 is stingent,verbose=2 gives op after each iteration

In [103]:
boruta_feature_selector.fit(start_x,start_y)

Iteration: 	1 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	2 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	3 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	4 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	5 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	6 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	7 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	8 / 50
Confirmed: 	9
Tentative: 	0
Rejected: 	0


BorutaPy finished running.

Iteration: 	9 / 50
Confirmed: 	9
Tentative: 	0
Rejected: 	0


BorutaPy(alpha=0.05,
         estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                          class_weight=None, criterion='gini',
                                          max_depth=None, max_features='auto',
                                          max_leaf_nodes=None, max_samples=None,
                                          min_impurity_decrease=0.0,
                                          min_impurity_split=None,
                                          min_samples_leaf=1,
                                          min_samples_split=2,
                                          min_weight_fraction_leaf=0.0,
                                          n_estimators=1000, n_jobs=None,
                                          oob_score=False,
                                          random_state=RandomState(MT19937) at 0x7FF281BB1270,
                                          verbose=0, warm_start=False),
         max_iter=50, n_estimators

In [104]:
boruta_feature_selector.support_ #False=Tentative,rejected True=Truly imp

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [105]:
start_x2=start.iloc[:,1:10]
df3 = pd.DataFrame({"Column_names":start_x2.columns, "Feature_importance":list(boruta_feature_selector.support_)})

In [106]:
df3

Column_names  Feature_importance
0              Clump Thickness                True
1      Uniformity of Cell Size                True
2     Uniformity of Cell Shape                True
3            Marginal Adhesion                True
4  Single Epithelial Cell Size                True
5                  Bare Nuclei                True
6              Bland Chromatin                True
7              Normal Nucleoli                True
8                      Mitoses                True

In [107]:
#6th method rfe
#recursively removes features,works out combination of attributes which gives max accuracy after removing
from sklearn.feature_selection import RFE
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier

In [108]:
svm = LinearSVC()
rfe = RFE(svm, 1) #runs on top of SVM,Top 5 imp features

In [109]:
rfe.fit(cr_x, cr_y)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarn

RFE(estimator=LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
                        intercept_scaling=1, loss='squared_hinge',
                        max_iter=1000, multi_class='ovr', penalty='l2',
                        random_state=None, tol=0.0001, verbose=0),
    n_features_to_select=1, step=1, verbose=0)

In [110]:
rfe.support_

array([False, False, False, False, False, False,  True, False])

In [111]:
cr_x.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [112]:
dt = DecisionTreeClassifier()
rfe_dt = RFE(dt, 7)#5 most important
rfe_dt.fit(cr_x, cr_y)

RFE(estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                     criterion='gini', max_depth=None,
                                     max_features=None, max_leaf_nodes=None,
                                     min_impurity_decrease=0.0,
                                     min_impurity_split=None,
                                     min_samples_leaf=1, min_samples_split=2,
                                     min_weight_fraction_leaf=0.0,
                                     presort='deprecated', random_state=None,
                                     splitter='best'),
    n_features_to_select=7, step=1, verbose=0)

In [113]:
rfe.support_

array([False, False, False, False, False, False,  True, False])

In [114]:
##REGRESSION
start_up = pd.read_csv("50_Startups.csv")

In [115]:
start_up.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [116]:
start_up.shape

(50, 5)

In [117]:
start_up_x = start_up.iloc[:, 0:3]
start_up_y = start_up.iloc[:,-1]

In [118]:
start_up_x.head()

R&D Spend  Administration  Marketing Spend
0  165349.20       136897.80        471784.10
1  162597.70       151377.59        443898.53
2  153441.51       101145.55        407934.54
3  144372.41       118671.85        383199.62
4  142107.34        91391.77        366168.42

In [119]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
rfe1 = RFE(reg, 2)


In [120]:
rfe1.fit(start_up_x, start_up_y)

RFE(estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                               normalize=False),
    n_features_to_select=2, step=1, verbose=0)

In [121]:
rfe1.get_support()

array([ True, False,  True])

In [122]:
start_up_x.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend'], dtype='object')

In [123]:
##LASSOS METHOD
from sklearn.linear_model import Lasso
lasso = Lasso()
lasso.fit(start_up_x, start_up_y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [124]:
lasso.coef_

array([ 0.80571505, -0.02681597,  0.02722806])

Coefficients Of our regressions Variable.If 0 doesnt matter as y=m1x1+m2x2+.....
thus if 0 not important else important

In [125]:
start_up_x.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend'], dtype='object')

In [126]:
feature_imp = pd.DataFrame({"Feature":start_up_x.columns, "Coeffs":list(lasso.coef_)})

In [127]:
feature_imp

Feature    Coeffs
0        R&D Spend  0.805715
1   Administration -0.026816
2  Marketing Spend  0.027228