In [6]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.tree import DecisionTreeClassifier

In [7]:
cr = pd.read_csv("Social_Network_Ads.csv")

In [8]:
select = SelectFromModel(RandomForestClassifier(n_estimators=100))

In [9]:
cr.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [10]:
cr.shape

(400, 3)

In [15]:
select = SelectFromModel(RandomForestClassifier(n_estimators=100))
cr_x = cr.iloc[:, 0:2]
cr_y = cr.iloc[:, -1]

In [16]:
select.fit(cr_x, cr_y)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                                 class_weight=None,
                                                 criterion='gini',
                                                 max_depth=None,
                                                 max_features='auto',
                                                 max_leaf_nodes=None,
                                                 max_samples=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=100, n_jobs=None,
                                                 oob_score=False,

In [17]:
select.get_support()

array([ True, False])

In [18]:
cr_x.columns

Index(['Age', 'EstimatedSalary'], dtype='object')

In [19]:
list1 = list(select.get_support())

In [20]:
list1

[True, False]

In [21]:
#True is importane and 0 isnt important
df_feat_imp = pd.DataFrame({"Feature_Name":cr_x.columns, "Importance":list1})
df_feat_imp

Feature_Name  Importance
0              Age        True
1  EstimatedSalary       False

In [22]:
df_feat_imp.sort_values(["Importance"], ascending = False)

Feature_Name  Importance
0              Age        True
1  EstimatedSalary       False

In [23]:
#Second Method
rfc = RandomForestClassifier()
rfc.fit(cr_x, cr_y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [24]:
rfc.feature_importances_ #Higher score more important feature

array([0.52557818, 0.47442182])

In [25]:
cr_x.columns

Index(['Age', 'EstimatedSalary'], dtype='object')

In [26]:
df1 = pd.DataFrame({"feature_name": cr_x.columns, "Importance":list(rfc.feature_importances_)})

In [27]:
df1

feature_name  Importance
0              Age    0.525578
1  EstimatedSalary    0.474422

In [28]:
df1.sort_values(["Importance"], ascending=False)

feature_name  Importance
0              Age    0.525578
1  EstimatedSalary    0.474422

In [29]:
##3rd
from sklearn.tree import DecisionTreeClassifier

In [30]:
dt = DecisionTreeClassifier()
dt.fit(cr_x, cr_y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [31]:
dt.feature_importances_

array([0.52822844, 0.47177156])

In [32]:
dt.feature_importances_.sum()

1.0

In [33]:
#4th CHIsquare
test = SelectKBest(score_func=chi2, k="all")#to check corelation on all k features


In [34]:
fited = test.fit(cr_x, cr_y)

In [36]:
fited.scores_

array([4.51155226e+02, 8.72013169e+05])

In [37]:
list(fited.scores_)#Higher value more important

[451.15522589349507, 872013.1692307568]

In [38]:
df2 = pd.DataFrame({"Features":cr_x.columns, "Imp":list(fited.scores_)})
df2

Features            Imp
0              Age     451.155226
1  EstimatedSalary  872013.169231

In [39]:
df2.sort_values(["Imp"],ascending=False)

Features            Imp
1  EstimatedSalary  872013.169231
0              Age     451.155226

In [54]:
#Boruta Runs multiple random forests giving 3 values Confirm,Tentative,Rejected
start = pd.read_csv("Data.csv")
start.head()


Sample code number  Clump Thickness  ...  Mitoses  Class
0             1000025                5  ...        1      2
1             1002945                5  ...        1      2
2             1015425                3  ...        1      2
3             1016277                6  ...        1      2
4             1017023                4  ...        1      2

[5 rows x 11 columns]

In [55]:
start_x = start.iloc[:,1:10]
start_y = start.iloc[:, -1]

In [56]:
start.shape

(683, 11)

In [57]:
import numpy as np
start_x = np.array(start_x)
start_y = np.array(start_y)

In [58]:
!pip install boruta

In [59]:
from boruta import BorutaPy

In [60]:
rf = RandomForestClassifier()

In [61]:
boruta_feature_selector = BorutaPy(rf, random_state=111,max_iter=50,perc=100,verbose=2)#Runs random Forest for 50times,perc=Be sure when selecting feature 100 is stingent,verbose=2 gives op after each iteration

In [62]:
boruta_feature_selector.fit(start_x,start_y)

Iteration: 	1 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	2 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	3 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	4 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	5 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	6 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	7 / 50
Confirmed: 	0
Tentative: 	9
Rejected: 	0
Iteration: 	8 / 50
Confirmed: 	9
Tentative: 	0
Rejected: 	0


BorutaPy finished running.

Iteration: 	9 / 50
Confirmed: 	9
Tentative: 	0
Rejected: 	0


BorutaPy(alpha=0.05,
         estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                          class_weight=None, criterion='gini',
                                          max_depth=None, max_features='auto',
                                          max_leaf_nodes=None, max_samples=None,
                                          min_impurity_decrease=0.0,
                                          min_impurity_split=None,
                                          min_samples_leaf=1,
                                          min_samples_split=2,
                                          min_weight_fraction_leaf=0.0,
                                          n_estimators=1000, n_jobs=None,
                                          oob_score=False,
                                          random_state=RandomState(MT19937) at 0x7F857CB446B0,
                                          verbose=0, warm_start=False),
         max_iter=50, n_estimators

In [63]:
boruta_feature_selector.support_ #False=Tentative,rejected True=Truly imp

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [65]:
start_x2=start.iloc[:,1:10]
df3 = pd.DataFrame({"Column_names":start_x2.columns, "Feature_importance":list(boruta_feature_selector.support_)})

In [66]:
df3

Column_names  Feature_importance
0              Clump Thickness                True
1      Uniformity of Cell Size                True
2     Uniformity of Cell Shape                True
3            Marginal Adhesion                True
4  Single Epithelial Cell Size                True
5                  Bare Nuclei                True
6              Bland Chromatin                True
7              Normal Nucleoli                True
8                      Mitoses                True

In [67]:
#6th method rfe
#recursively removes features,works out combination of attributes which gives max accuracy after removing
from sklearn.feature_selection import RFE
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier

In [72]:
svm = LinearSVC()
rfe = RFE(svm, 1) #runs on top of SVM,Top 5 imp features

In [73]:
rfe.fit(cr_x, cr_y)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


RFE(estimator=LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
                        intercept_scaling=1, loss='squared_hinge',
                        max_iter=1000, multi_class='ovr', penalty='l2',
                        random_state=None, tol=0.0001, verbose=0),
    n_features_to_select=1, step=1, verbose=0)

In [74]:
rfe.support_

array([ True, False])

In [75]:
cr_x.columns

Index(['Age', 'EstimatedSalary'], dtype='object')

In [77]:
dt = DecisionTreeClassifier()
rfe_dt = RFE(dt, 5)#5 most important
rfe_dt.fit(cr_x, cr_y)

RFE(estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                     criterion='gini', max_depth=None,
                                     max_features=None, max_leaf_nodes=None,
                                     min_impurity_decrease=0.0,
                                     min_impurity_split=None,
                                     min_samples_leaf=1, min_samples_split=2,
                                     min_weight_fraction_leaf=0.0,
                                     presort='deprecated', random_state=None,
                                     splitter='best'),
    n_features_to_select=5, step=1, verbose=0)

In [78]:
rfe.support_

array([ True, False])

In [79]:
##REGRESSION
start_up = pd.read_csv("50_Startups.csv")

In [80]:
start_up.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [82]:
start_up.shape

(50, 5)

In [83]:
start_up_x = start_up.iloc[:, 0:3]
start_up_y = start_up.iloc[:,-1]

In [84]:
start_up_x.head()

R&D Spend  Administration  Marketing Spend
0  165349.20       136897.80        471784.10
1  162597.70       151377.59        443898.53
2  153441.51       101145.55        407934.54
3  144372.41       118671.85        383199.62
4  142107.34        91391.77        366168.42

In [90]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
rfe1 = RFE(reg, 2)


In [92]:
rfe1.fit(start_up_x, start_up_y)

RFE(estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                               normalize=False),
    n_features_to_select=2, step=1, verbose=0)

In [93]:
rfe1.get_support()

array([ True, False,  True])

In [94]:
start_up_x.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend'], dtype='object')

In [95]:
##LASSOS METHOD
from sklearn.linear_model import Lasso
lasso = Lasso()
lasso.fit(start_up_x, start_up_y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [96]:
lasso.coef_

array([ 0.80571505, -0.02681597,  0.02722806])

Coefficients Of our regressions Variable.If 0 doesnt matter as y=m1x1+m2x2+.....
thus if 0 not important else important

In [97]:
start_up_x.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend'], dtype='object')

In [98]:
feature_imp = pd.DataFrame({"Feature":start_up_x.columns, "Coeffs":list(lasso.coef_)})

In [99]:
feature_imp

Feature    Coeffs
0        R&D Spend  0.805715
1   Administration -0.026816
2  Marketing Spend  0.027228